version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn sprint_names.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/www/sprint-names/static/
      - ./data:/code/sprint_names/data
    ports:
      - 8000:8000
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - static_volume:/srv/www/sprint-names/static/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
