version: '3'

services:
  web:
    build: ./app
    command: gunicorn sprint_names.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/www/sprint-names/static/
      - ./data:/code/sprint_names/data
    networks:
      - proxy
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - static_volume:/srv/www/sprint-names/static/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sprintnames.rule=Host(`sprintnames.thesystemisdown.lol`)"
      - "traefik.http.routers.sprintnames.entrypoints=websecure"
      - "traefik.http.routers.sprintnames.tls=true"
      - "traefik.http.routers.sprintnames.tls.certresolver=myresolver"
      - "traefik.http.routers.sprintnames.service=sprintnames-service"
      - "traefik.http.services.sprintnames-service.loadbalancer.server.port=80"
    networks:
      - proxy
networks:
  proxy:
    external: true
volumes:
  static_volume:
