version: '3.8'

services:
  web:
    build: .
    command: gunicorn sprint_names.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/srv/www/sprint-names/static/
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/srv/www/sprint-names/static/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
