# Generated by Django 3.1.3 on 2020-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='names',
            name='used_at',
            field=models.DateField(null=True),
        ),
    ]
